export {
    locationsAPI,
    useFetchCountriesQuery,
    // useFetchRegionStatesQuery,
    // useFetchProvincesQuery,
    // useFetchMunicipalitiesQuery,
    // useFetchBarangaysQuery,
    useActionLocationsMutation,
} from "./locationsAPI";

export {
    useLocations,
    useLocationsService,
    // useCountries,
    // useRegionStates,
    // useProvinces,
    // useMunicipalities,
    // useBarangays,
    type Country,
    type RegionState,
    type Province,
    type Municipality,
    type Barangay,
    type CountriesRequest,
    type RegionStatesRequest,
    type ProvincesRequest,
    type MunicipalitiesRequest,
    type BarangaysRequest,
    type CountriesResponse,
    type RegionStatesResponse,
    type ProvincesResponse,
    type MunicipalitiesResponse,
    type BarangaysResponse,
} from "./use-locations";